version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: goods-warehouse
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      back-network:
        aliases:
          - postgres
    restart: unless-stopped
  backend:
    container_name: backend
    image: backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      back-network:
        aliases:
          - backend
    depends_on:
      - postgres
    restart: unless-stopped
networks:
  back-network:
    driver: bridge
volumes:
  postgres:
    driver: local