server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
spring:
  liquibase:
    enabled: true
  application:
    name: backend
  datasource:
    password: password
    username: goodswarehouse-backend
    url: jdbc:postgresql://postgres:5432/goodswarehouse-backend
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  output:
    ansi:
      enabled: always
