spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:PLAINTEXT_HOST://localhost:9091}
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/goods-warehouse
  jpa:
    hibernate:
      ddl-auto: validate
app:
  kafka:
    enabled: true
  scheduling:
    enabled: false
minio:
  url: ${MINIO_ENDPOINT:http://localhost:9000}