spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:PLAINTEXT_HOST://localhost:9091}
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: test
    password: test
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
app:
  kafka:
    enabled: false
  scheduling:
    enabled: false