server:
  port: ${APP_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
spring:
  kafka:
    template:
      default-topic: ${KAFKA_TOPIC:test-topic}
    consumer:
      group-id: ${KAFKA_GROUP_ID:group-id}
  liquibase:
    enabled: true
  application:
    name: ${APP_NAME:backend}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  output:
    ansi:
      enabled: always
app:
  headers:
    currency: "currency"
  scheduling:
    optimization: true
    price_increase: 0.2
    period: 5000
  caching:
    ttl: 60000
rest:
  currency-service:
    host: ${CURRENCY_SERVICE_HOST:http://localhost:8081}
    retry-count: 2
    methods:
      get-currency: /api/currencies/get
    mock:
      enabled: true
  account-service:
    host: ${ACCOUNT_SERVICE_HOST:http://localhost:8082}
    retry-count: 2
    methods:
      get-account-number: /api/account/number
    mock:
      enabled: true
  crm-service:
    host: ${CRM_SERVICE_HOST:http://localhost:8082}
    retry-count: 2
    methods:
      get-inn: /api/inn
    mock:
      enabled: true
