spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:PLAINTEXT_HOST://kafka:9091}
  datasource:
    username: goods-warehouse
    password: 200214
    url: jdbc:postgresql://postgres:5432/goods-warehouse
  jpa:
    hibernate:
      ddl-auto: validate
app:
  kafka:
    enabled: true
  scheduling:
    enabled: true