spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: test
    password: test
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
app:
  scheduling:
    enabled: false
minio:
  url: ${MINIO_ENDPOINT:http://localhost:9000}