#spring:
#  datasource:
#    url: jdbc:h2:mem:goods-warehouse
#    driverClassName: org.h2.Driver
#    username: admin
#    password: 200214
#  h2:
#    console:
#      enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: create
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/goods-warehouse
  jpa:
    hibernate:
      ddl-auto: validate
app:
  scheduling:
    enabled: false