spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/goods-warehouse
  jpa:
    hibernate:
      ddl-auto: validate
app:
  scheduling:
    enabled: false