server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
spring:
  liquibase:
    enabled: true
  application:
    name: backend
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  output:
    ansi:
      enabled: always
app:
  headers:
    currency: "currency"
  scheduling:
    optimization: true
    price_increase: 0.2
    period: 5000
  caching:
    ttl: 60000
currency-service:
  host: http://localhost:8081
  retry-count: 2
  methods:
    get-currency: /api/currencies/get
  mock:
    enabled: true
