server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
spring:
  liquibase:
    enabled: true
  application:
    name: backend
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  output:
    ansi:
      enabled: always
app:
  scheduling:
    optimization: true
    price_increase: 0.2
    period: 5000

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/goodswarehouse-backend
app:
  scheduling:
    enabled: false

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    password: password
    username: goodswarehouse-backend
    url: jdbc:postgresql://postgres:5432/goodswarehouse-backend
app:
  scheduling:
    enabled: true
