server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
spring:
  liquibase:
    enabled: true
  application:
    name: backend
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  output:
    ansi:
      enabled: always
app:
  scheduling:
    optimization: true
    price_increase: 0.2
    period: 5000
