server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
spring:
  liquibase:
    enabled: true
  application:
    name: backend
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  output:
    ansi:
      enabled: always
app:
  scheduling:
    optimization: true
    price_increase: 0.2
    period: 5000
headers:
  keys:
    currency: "currency"
caching:
  ttl: 60000
  currency:
    name: currencyCache
    key: currencyExchange
  service-connection-enabled: true
currency-service:
  host: http://localhost:8081
  methods:
    get-currency: /api/currencies/get
web-client:
  retry-count: 2
